FROM almalinux:9
CMD [ "ping","-c5","google.com" ]  

#using this image we can ping any site 

# docker build -t entrypoint:1.1
# docker run entrypoint:1.1 --- now it will ping the google.com
# docker run entrypoint:1.1 ping -c5 yahoo.com  >>>> now it will override the CMD , it will connect yahoo.com

